# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

jobs:
  build: # Not a real build, but it could be
    docker:
      - image: cimg/base:2024.02
    environment:
      OPENFIRE_VERSION_DOTS: "4.8.1"
      OPENFIRE_VERSION_DASHES: "4_8_1"
    steps:
      - checkout
      - restore_cache:
          keys:
            - tar-{{ .Environment.OPENFIRE_VERSION_DOTS }}
      - run: 
          name: 'Fetch Openfire'
          command: |
            if [ ! -f openfire.tar.gz ]; then
              curl -L "https://github.com/igniterealtime/Openfire/releases/download/v$OPENFIRE_VERSION_DOTS/openfire_$OPENFIRE_VERSION_DASHES.tar.gz" -o openfire.tar.gz
            fi
      - run:
          name: 'Extract Openfire'
          command: tar -xzf openfire.tar.gz
      - save_cache:
          paths:
            - openfire.tar.gz
          key: tar-{{ .Environment.OPENFIRE_VERSION_DOTS }}
      - persist_to_workspace:
          root: .
          paths:
            - .github
            - openfire
  test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - attach_workspace:
          at: .
      - run: 
          name: 'Start Openfire'
          command: .github/actions/startserver-action/startCIServer.sh -i "127.0.0.1" -h "example.org" -b "openfire"
          background: true
      - run:
          name: 'Wait for Openfire to start'
          command: sleep 30     # I'm really, really sorry,
      - run:
          name: 'Run Compliance Tests'
          command: echo 'Tests go here'
      - run:
          name: 'Stop Openfire'
          command: .github/actions/stopserver-action/stopCIServer.sh


workflows:
  build-openfire:
    jobs:
      - build
      - test:
          requires:
            - build
