# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
    interop-test: interop-test/tests@dev:alpha

jobs:
  build: # Not a real build, but it could be
    docker:
      - image: cimg/base:2024.02
    environment:
      OPENFIRE_VERSION_DOTS: "4.8.3"
      OPENFIRE_VERSION_DASHES: "4_8_3"
    steps:
      - checkout
      - restore_cache:
          keys:
            - tar-{{ .Environment.OPENFIRE_VERSION_DOTS }}
      - run: 
          name: 'Fetch Openfire'
          command: |
            if [ ! -f openfire.tar.gz ]; then
              curl -L "https://github.com/igniterealtime/Openfire/releases/download/v$OPENFIRE_VERSION_DOTS/openfire_$OPENFIRE_VERSION_DASHES.tar.gz" -o openfire.tar.gz
            fi
      - run:
          name: 'Extract Openfire'
          command: tar -xzf openfire.tar.gz
      - save_cache:
          paths:
            - openfire.tar.gz
          key: tar-{{ .Environment.OPENFIRE_VERSION_DOTS }}
      - persist_to_workspace:
          root: .
          paths:
            - scripts
            - openfire
  test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - attach_workspace:
          at: .
      - run: 
          name: 'Start Openfire'
          command: |
            scripts/startCIServer.sh -i "127.0.0.1" -h "example.org" -b "openfire"
            sleep 6000
          background: true
      - run:
          name: 'Wait for Openfire Admin Console to be available'
          command: wget --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 -t 10 http://localhost:9090/login.jsp
      - interop-test/test:
          adminAccountUsername: 'admin'
          adminAccountPassword: 'admin'
          disabledTests: 'EntityCapsTest,SoftwareInfoIntegrationTest,XmppConnectionIntegrationTest,StreamManagementTest,WaitForClosingStreamElementTest,IoTControlIntegrationTest,ModularXmppClientToServerConnectionLowLevelIntegrationTest'


workflows:
  build-openfire:
    jobs:
      - build
      - test:
          requires:
            - build
